# .github/workflows/build.yml
name: Build (Vite)

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  WORKDIR: client # ถ้าโปรเจกต์อยู่ราก ให้เปลี่ยนเป็น "."

  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.WORKDIR }}/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run -s lint || true

      - name: Typecheck (optional)
        run: npm run -s typecheck || true

      - name: Build
        run: npm run build

      - name: Upload dist artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ env.WORKDIR }}/dist
          retention-days: 7
